# Generated by Django 5.2.8 on 2026-02-04 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Başlangıç Tarihi')),
                ('level', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6'), ('T7', 'T7'), ('T8', 'T8'), ('T9', 'T9'), ('T10', 'T10'), ('T11', 'T11'), ('T12', 'T12'), ('T13', 'T13'), ('T14', 'T14'), ('T15', 'T15'), ('T16', 'T16'), ('T17', 'T17')], max_length=5, verbose_name='Seviye / Kur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Kayıt',
                'verbose_name_plural': 'Kayıtlar',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Program Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programlar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Adı Soyadı')),
                ('national_id', models.CharField(max_length=11, unique=True, verbose_name='T.C Kimlik No')),
                ('birth_date', models.DateField(verbose_name='Doğum Tarihi')),
                ('gender', models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın'), ('O', 'Diğer / Belirtmek İstemiyorum')], max_length=1, verbose_name='Cinsiyet')),
                ('school', models.CharField(blank=True, max_length=200, null=True, verbose_name='Okulu')),
                ('school_class', models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('5', '5. Sınıf'), ('6', '6. Sınıf'), ('7', '7. Sınıf'), ('8', '8. Sınıf'), ('9', '9. Sınıf'), ('10', '10. Sınıf'), ('11', '11. Sınıf'), ('12', '12. Sınıf'), ('MEZUN', 'Mezun')], max_length=10, verbose_name='Sınıfı')),
                ('emergency_contact_name', models.CharField(max_length=150, verbose_name='Acil Durum Kişi Adı')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Acil Durum Telefonu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Ücret')),
                ('payment_method', models.CharField(choices=[('nakit', 'Nakit'), ('havale', 'Havale / EFT'), ('taksit', 'Taksit'), ('kredi_karti', 'Kredi Kartı')], max_length=20, verbose_name='Ödeme Şekli')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='kurbutikegitimkayitotomasyonapp.enrollment')),
            ],
            options={
                'verbose_name': 'Ödeme Planı',
                'verbose_name_plural': 'Ödeme Planları',
            },
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default=django.utils.timezone.now, verbose_name='Vade Tarihi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama')),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='kurbutikegitimkayitotomasyonapp.paymentplan')),
            ],
            options={
                'verbose_name': 'Ödeme / Taksit',
                'verbose_name_plural': 'Ödemeler / Taksitler',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='kurbutikegitimkayitotomasyonapp.program'),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Veli Adı Soyadı')),
                ('national_id', models.CharField(max_length=11, verbose_name='Veli T.C Kimlik No')),
                ('relation', models.CharField(choices=[('anne', 'Anne'), ('baba', 'Baba'), ('veli', 'Veli'), ('diger', 'Diğer')], max_length=20, verbose_name='Yakınlık Derecesi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta Adresi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres Bilgisi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='kurbutikegitimkayitotomasyonapp.student')),
            ],
            options={
                'verbose_name': 'Veli',
                'verbose_name_plural': 'Veliler',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='kurbutikegitimkayitotomasyonapp.student'),
        ),
    ]
