# Generated by Django 5.2.8 on 2026-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurbutikegitimkayitotomasyonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='installment_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Sadece taksitli ödemelerde doldurun.', null=True, verbose_name='Taksit Sayısı (2-10)'),
        ),
    ]
