# Generated by Django 5.2.8 on 2026-02-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurbutikegitimkayitotomasyonapp', '0002_paymentplan_installment_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentinstallment',
            options={'ordering': ['id'], 'verbose_name': 'Ödeme / Taksit', 'verbose_name_plural': 'Ödemeler / Taksitler'},
        ),
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='due_date',
        ),
    ]
